BUG: Uninstall existing ITK packages in GHA env before testing
Suppresses the message:
```
ERROR: pip's dependency resolver does not currently take into account
all the packages that are installed. This behaviour is the source of the
following dependency conflicts.
```